# Generated by Django 4.2.26 on 2025-12-01 20:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True, null=True)),
                ('api_key', models.CharField(editable=False, max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('member', 'Member'), ('viewer', 'Viewer')], default='viewer', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('invited_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_invitations', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='core.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('project', 'user')},
            },
        ),
        migrations.CreateModel(
            name='ErrorEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(db_index=True, max_length=64)),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('event_type', models.CharField(choices=[('exception', 'Exception'), ('message', 'Message')], db_index=True, default='exception', max_length=32)),
                ('level', models.CharField(blank=True, choices=[('debug', 'Debug'), ('info', 'Info'), ('warning', 'Warning'), ('error', 'Error')], db_index=True, max_length=16, null=True)),
                ('exception_type', models.CharField(blank=True, db_index=True, max_length=128, null=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('stacktrace', models.TextField(blank=True, null=True)),
                ('tags', models.JSONField(blank=True, default=dict)),
                ('extra', models.JSONField(blank=True, default=dict)),
                ('raw_json', models.JSONField(blank=True, null=True)),
                ('environment', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('service_name', models.CharField(blank=True, db_index=True, max_length=128, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='errors', to='core.project')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at', 'project'], name='core_errore_created_7a6369_idx'), models.Index(fields=['event_type', 'project'], name='core_errore_event_t_579a38_idx'), models.Index(fields=['exception_type', 'project'], name='core_errore_excepti_36656c_idx')],
            },
        ),
    ]
